var world_seeing = ['Brazil', 'Australia', 'USA', 'Canada', 'Dubai'];
console.log(world_seeing);
world_seeing.sort();
console.log(world_seeing);
world_seeing.reverse();
console.log(world_seeing);
world_seeing.reverse();
console.log(world_seeing);
world_seeing.sort();
console.log(world_seeing);
